version: "3"
services:
  php:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
      args:
        - USER_ID=${CURRENT_UID}
        - GROUP_ID=${CURRENT_GID}
    volumes:
      - ../:/app
    depends_on:
      mysql:
        condition: service_healthy
    container_name: symfony_docker_skeleton_php

  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 127.0.0.1:8099:80
    volumes:
      - ../:/app:cached
    container_name: symfony_docker_skeleton_nginx
    depends_on:
      - php

  mysql:
    image: mysql:latest
    volumes:
      - symfony_docker_skeleton_database:/var/lib/mysql
    ports:
      - 127.0.0.1:3391:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony_docker_skeleton
    container_name: symfony_docker_skeleton_mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

volumes:
  symfony_docker_skeleton_database: